/*
 * SYSTICK_cfg.h
 *
 *  Created on: Nov 26, 2023
 *      Author: moham
 */

#ifndef MCAL_SYSTICK_SYSTICK_CFG_H_
#define MCAL_SYSTICK_SYSTICK_CFG_H_

/*OPTIONS : 1-STK_AHB 2-STK_AHB_DIV_8*/
#define STK_CLK_SOURCE 		STK_AHB_DIV_8

/*OPTIONS : 1-ENABLE 2-DISABLE*/
#define STK_INTERRUPT_EN 	DISABLE

#endif /* MCAL_SYSTICK_SYSTICK_CFG_H_ */
