CC=arm-none-eabi-
CFLAGS =-mcpu=cortex-m3 -g -gdwarf-2
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ= $(SRC:.c=.o)
AS = $(wildcard *.s)
ASOBJ = $(AS:.s=.o)
all: Pressure-Detection.hex
%.o : %.c 
	$(CC)gcc.exe  $(INCS) $(CFLAGS) -c $< -o $@

Pressure-Detection.elf : $(OBJ) 
	$(CC)ld.exe -T Linker_Script.ld $(OBJ)  -o $@ -Map=Map_file.Map

Pressure-Detection.hex : Pressure-Detection.elf 
	$(CC)objcopy.exe -O binary $< $@
	@echo "Everything is build"
clean:
	rm main.o 
	rm startup.o 
	rm Alarm_Actuator_Driver.o 
	rm Alarm_Monitor.o 
	rm driver.o 
	rm Main_Algorithm.o 
	rm Pressure_sensor_driver.o 
	rm Pressure-Detection.elf 
	rm Pressure-Detection.hex
	@echo "Everything clean"