/*
 * DAC_cfg.c
 *
 *  Created on: Jan 10, 2024
 *      Author: moham
 */

#include "../../LIB/STD_TYPES.h"
#include "../../MCAL/GPIO/GPIO_int.h"
#include "DAC_cfg.h"


MGPIO_Config_t dac_pins[DAC_RESOLUTION]={{GPIO_PORTA,PIN0,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0},
								{GPIO_PORTA,PIN1,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0},
								{GPIO_PORTA,PIN2,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0},
								{GPIO_PORTA,PIN3,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0},
								{GPIO_PORTA,PIN4,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0},
								{GPIO_PORTA,PIN5,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0},
								{GPIO_PORTA,PIN6,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0},
								{GPIO_PORTA,PIN7,GPIO_MODE_OUTPUT,GPIO_LOW,GPIO_PUSHPULL,GPIO_NO_PULL,0}};





